version: "3.7"
services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - traefik
    labels:
      - traefik.enable=false
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./redis:/var/lib/redis
    labels:
      - traefik.enable=false
    networks:
      - traefik
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - traefik
    depends_on:
      - db
      - redis
    labels:
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nc_redirect
      - traefik.http.routers.nextcloud.tls.certresolver=lets-encrypt
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.rule=Host(`${CLOUD_URL}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
      - "traefik.http.middlewares.nc_redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc_redirect.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc_redirect.redirectregex.replacement=https://$$1/remote.php/dav/"
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - TRUSTED_PROXIES=172.19.0.2/16
      - NEXTCLOUD_TRUSTED_DOMAINS=${CLOUD_URL}
      - OVERWRITEPROTOCOL=https
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  traefik:
    external: true 
