version: "3.7"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    command:
      - "--providers.docker.network=traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
    networks:
      - traefik
    restart: always
networks:
  traefik:
    external: true
